FROM node:18

# Install ffmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Workdir setup
WORKDIR /app
COPY . .

RUN npm install

CMD ["npm", "start"]
